### ISSUE TITLE
Was able to run everything. All of a sudden, I got this error. TypeError: expected str, bytes or os.PathLike object, not NoneType"

### ISSUE THREAD

**Issue by YuancXie** [PRBonn/4DMOS#35]
Thank you for sharing this example.

~/4DMOS$ python scripts/train.py
/home/yc/miniconda3/lib/python3.11/site-packages/MinkowskiEngine-0.5.4-py3.11-linux-x86_64.egg/MinkowskiEngine/__init__.py:36: UserWarning: The environment variable `OMP_NUM_THREADS` not set. MinkowskiEngine will automatically set `OMP_NUM_THREADS=16`. If you want to set `OMP_NUM_THREADS` manually, please export it on the command line before running a python script. e.g. `export OMP_NUM_THREADS=12; python your_program.py`. It is recommended to set it below 24.
  warnings.warn(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA GeForce RTX 3080') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
Traceback (most recent call last):
  File "/home/yc/4DMOS/scripts/train.py", line 87, in <module>
    main()
  File "/home/yc/miniconda3/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yc/miniconda3/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/yc/miniconda3/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yc/miniconda3/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yc/4DMOS/scripts/train.py", line 83, in main
    trainer.fit(model, data, ckpt_path=checkpoint)
  File "/home/yc/miniconda3/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/yc/miniconda3/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yc/miniconda3/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/yc/miniconda3/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 950, in _run
    call._call_setup_hook(self)  # allow user to setup lightning_module in accelerator environment
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yc/miniconda3/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 92, in _call_setup_hook
    _call_lightning_datamodule_hook(trainer, "setup", stage=fn)
  File "/home/yc/miniconda3/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 179, in _call_lightning_datamodule_hook
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/yc/4DMOS/src/mos4d/datasets/datasets.py", line 47, in setup
    train_set = KittiSequentialDataset(self.cfg, split="train")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yc/4DMOS/src/mos4d/datasets/datasets.py", line 172, in __init__
    path_to_seq = os.path.join(self.root_dir, seqstr)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "< frozen p osixpath>", line 76, in join
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by benemer** [comment]
The dataloader can not find your data. How is your data organized, how does your config look like and did you specify the `DATA` variable in your environment?

**Comment by YuancXie** [comment]
Thank you for your prompt response. It was a silly mistake I made.
I did "DATA=/home/yc/4DMOS/dataset/sequences" and forgot the "export" at the beginning. That did not trigger any errors/warnings. 
Now the problem is solved. Thank you again.
